baseURL: https://isurubuddhika.dev/
languageCode: en-us
title: Techie with a Conscience
copyright: "&copy; 2026 [Isuru Buddhika Pathirana](/)"
theme: "PaperMod"
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

params:
    showShareButtons: true
    shareButtons: [twitter, linkedin, reddit, whatsapp, telegram]
    showReadingTime: true
    showTags: true
    showBreadcrumbs: false
    defaultTheme: dark
    disableThemeToggle: false
    label:
      # icon: /blog_icon.png
      # text: "<span class='brace'>{</span> isuru buddhika <span class='surname'>pathirana</span> <span class='brace'>}</span>"
      text: "<span class='brace'>{</span> isurubuddhika.dev <span class='brace'>}</span>"

    profileMode:
        enabled: true
        title: "Hi, I'm Isuru \U0001F44B" # optional default will be site title
        subtitle: >
            | Fullstack Engineer, Techie with a Conscience |  
            
            Loves Cofee, Code, Books, Movies and Philosophy  

            Coder by Choice  

        imageUrl: "https://pbs.twimg.com/profile_images/994521163916169217/fayMS6hm.jpg" # optional
        imageTitle: "profile-img" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        badges:
          - name: Java
          - name: Spring
          - name: ReactJS
          - name: Angular
          - name: MySQL
          - name: Postgres
          - name: Python
          - name: Jenkins
          - name: Docker
          - name: Linux
          - name: BASH
          - name: nginx
          - name: apache
          - name: Tomcat
          - name: AWS
          - name: Kafka

    socialIcons: # optional
        - name: "linkedin"
          url: "https://www.linkedin.com/in/isurubuddhika/"
        - name: "stackoverflow"
          url: "https://stackoverflow.com/users/1979249/isuru-pathirana"
        - name: "twitter"
          url: "https://twitter.com/isurunix"

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: 1
        - identifier: blog
          name: Blog
          url: /posts/
          weight: 2
        - identifier: about
          name: About
          url: about
          weight: 3
        - identifier: work
          name: Work
          url: work
          weight: 4
        - identifier: notes
          name: Notes
          url: https://notes.isurubuddhika.dev/
          weight: 5

taxonomies:
    category: categories
    tag: tags
    series: series

